apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-service"
spec:
  type:
    "{ .Values.service.type }": null
  ports:
    - port:
        "{ .Values.service.port }": null
      targetPort: 80
  selector:
    app:
      "{ .Release.Name }": null
