# Production environment configuration
global:
  environment: prod

replicaCount: 3

image:
  tag: stable
  pullPolicy: Always

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 2000

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: hello-world.company.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: hello-world-tls
      hosts:
        - hello-world.company.com

monitoring:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: 15s
    scrapeTimeout: 14s

# Production-specific settings
production:
  # High availability settings
  highAvailability:
    enabled: true
    minReplicas: 3
    zones:
      - zone1
      - zone2
      - zone3
  
  # Backup configuration
  backup:
    enabled: true
    schedule: "0 2 * * *"
    retention: 30d
  
  # Security settings
  security:
    networkPolicy:
      enabled: true
    podSecurityPolicy:
      enabled: true
    seccompProfile:
      enabled: true
  
  # Monitoring and alerting
  monitoring:
    alerts:
      enabled: true
      pagerDuty:
        enabled: true
    logging:
      retention: 30d
      archival: true